# Generated by Django 2.1 on 2018-09-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='contents',
        ),
        migrations.DeleteModel(
            name='ContentItem',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
